// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiJPrNb8JlHyjUz9BBoMt_wXuX3nOnubw',
    appId: '1:662285809694:web:26c5806ac3cb317728960f',
    messagingSenderId: '662285809694',
    projectId: 'library-management-syste-7b865',
    authDomain: 'library-management-syste-7b865.firebaseapp.com',
    storageBucket: 'library-management-syste-7b865.firebasestorage.app',
    measurementId: 'G-876XSTHSEH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk8NKkWR9DLN_5EqD-2KXqf4S41VteQ1k',
    appId: '1:662285809694:android:118921042d85459128960f',
    messagingSenderId: '662285809694',
    projectId: 'library-management-syste-7b865',
    storageBucket: 'library-management-syste-7b865.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiJPrNb8JlHyjUz9BBoMt_wXuX3nOnubw',
    appId: '1:662285809694:web:bfb6a202ad776d5428960f',
    messagingSenderId: '662285809694',
    projectId: 'library-management-syste-7b865',
    authDomain: 'library-management-syste-7b865.firebaseapp.com',
    storageBucket: 'library-management-syste-7b865.firebasestorage.app',
    measurementId: 'G-081T6QD1SX',
  );
}
